# Generated by Django 2.1.7 on 2020-04-24 16:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassifierVote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('classifier', models.CharField(max_length=250)),
                ('vote_id', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('asker', models.CharField(max_length=255)),
                ('question_text', models.CharField(max_length=250)),
                ('suggestion_correct', models.BooleanField(default=True)),
                ('corrected_answer', models.CharField(max_length=250)),
                ('votes', models.ManyToManyField(blank=True, null=True, to='bot.ClassifierVote')),
            ],
        ),
    ]
